name: Github CI
on:
  # Configura servidor de CI para executar o pipeline de tarefas abaixo (jobs) quando 
  # um push ou pull request for realizado tendo como alvo a branch main
  push:
    branches:
      - main
    paths:
      - '5-Demo-CI_Servidor_Integracao_Continua/demo-ci/**'  # Filtra apenas alterações nesta pasta
  pull_request:
    branches:
      - main
    paths:
      - '5-Demo-CI_Servidor_Integracao_Continua/demo-ci/**'  # Filtra apenas PRs que afetam esta pasta


jobs:
  pipeline:
    runs-on: ubuntu-latest # Os comandos serão executados em um sistema operacional Linux

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2 # Faz o checkout do código recebido

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1 # Configura o Java 1.8
        with:
          java-version: 1.8

      - name: Build
        working-directory: 5-Demo-CI_Servidor_Integracao_Continua/demo-ci # Executa os comandos nesta pasta
        run: mvn package -Dmaven.test.skip=true # Compila o código fonte

      - name: Unit Test
        working-directory: 5-Demo-CI_Servidor_Integracao_Continua/demo-ci
        run: mvn test # Executada os testes de unidade